# HSQLDB Configuration
spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver

# Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate.ddl-auto: create-drop

# graphql Configuration
  graphql:
    graphiql:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG